### ISSUE TITLE
[Docs] Octopus Pro wrong wiring diagram

### ISSUE THREAD

**Issue by thepete89** [Rat-OS/RatOS#11]
Hi,
I noticed that the Octopus Pro docs show the wrong board (Octopus 1.1) for both models.

This becomes clear when you look at the BLTouch/Inductive Probe connection, which is shown as being on the top right, while BTTs original documentation for the Octopus Pro shows it like this:

![grafik](https://user-images.githubusercontent.com/16416675/142068116-88b07d1c-3a90-4180-b2c1-f8aa2eae83cc.png)

This could lead to confusion and should be fixed in a future release.

**Comment by miklschmidt** [comment]
Fixed! Thank you :)
