### ISSUE TITLE
Build RatOS without Docker leads to unusable Image.

### ISSUE THREAD

**Issue by KwadFan** [Rat-OS/RatOS#12]
Hello Fellows,
this Issue is only to show up an error in your README.md.

If you follow the manual way you couldnt produce a usable Image, because "latest" is bullseye.
but since it is a fork of another project, similar to yours, the whole build chain is optimized to use "buster" Images as source.

See https://github.com/Rat-OS/RatOS/blob/729e17c143afdfbbe5b2b8824873d779052754cb/Makefile#L17

Regards and Merry Christmas ( soon ) ;)

**Comment by miklschmidt** [comment]
Thank you! I actually never use that i just run src/build_dist.sh instead, will look into it.

**Comment by miklschmidt** [comment]
fixed in the development branch 👍
