### ISSUE TITLE
z_tilt z_positions

### ISSUE THREAD

**Issue by mcjohn57** [Rat-OS/RatOS#13]
I believe RatOS could use a minor correction with z_tilt.  In the 500.cfg the z_tilt z_positions were:
	0,0
	250,500
	500,0
I believe these should be the center positions of the pivoting balls on the bed, so if my measurements and math is correct (pls verify) I believe they should be:
	-0.5,-0.75
	250,500.75
	500.5,0.75
I didn't run any math to know how much of an effect this actually has, but I can say after modifying this I don't think I've seen z_tilt run more than 2 times.

**Comment by miklschmidt** [comment]
It does not make any noticeable difference, i'm gonna close this for now.
