### ISSUE TITLE
Octopus 1.1/Pro Wiring Diagram change

### ISSUE THREAD

**Issue by Mitsuma** [Rat-OS/RatOS#17]
Small suggestion to remove the single mains wire after the SSR to not confuse Users why its there in the MCU wiring diagram.
Additional suggestion to add DC side +/- marking as not everybody knows about the hole being DC side.

![octopus-11-wiring](https://user-images.githubusercontent.com/8568089/148701362-ef741c9a-dc1d-454e-a69d-50596d9028f3.png)
![octopus-pro-wiring](https://user-images.githubusercontent.com/8568089/148701363-9f112f75-f1c6-4ff5-8a86-3120f0847dc0.png)

**Comment by miklschmidt** [comment]
Done 👍
