### ISSUE TITLE
Change Homing Behavior For GENERATE_SHAPER_GRAPHS

### ISSUE THREAD

**Issue by brenond** [Rat-OS/RatOS#19]
Some users have detachable accelerometers that mount directly to the printer's hotend.  Depending on the setup, this can end up closer to the bed than the ABL probe on the carriage, causing a crash if the printer homes after installing the accelerometer.

Currently, even if you have homed the printer beforehand and the printhead's location is known, the printer will still home all axes when the GENERATE_SHAPER_GRAPHS command is run, potentially causing a crash or cable snag.

This is not urgent, but would be a nice change when time allows.

**Comment by miklschmidt** [comment]
Hi! I agree, this is unfortunate, should add a check for whether the printer is already homed. Could you please recreate this issue over at https://github.com/Rat-OS/RatOS-configuration ? Thanks!
