### ISSUE TITLE
Different current values for z steppers in tmc2209.cfg

### ISSUE THREAD

**Issue by nilshomeier** [Rat-OS/RatOS#20]
Hi!

I noticed, that the current values for the z steppers in config/printers/v-core-3/tmc2209.cfg are different. Z and z2 are set to 1.0 while Z1 is set to 1.1.
I guess they should all be the same. Not sure if it makes much of a difference, but thought I mention it all the same.

![2022-01-11 07_56_33-VC3 - Brave](https://user-images.githubusercontent.com/10177623/148896434-dadacca2-e757-4594-bc4f-e92d17316077.jpg)

**Comment by miklschmidt** [comment]
Hi! These are now identical in RatOS v1.1.0+. The initial idea was that lower current was better for uncooled drivers, and Z1 (the rear stepper) carries more weight than the two in the front. They're now all at 1.1 in the base config.
