### ISSUE TITLE
My Octopus v1.1 dosn't come back after using the installer macro.

### ISSUE THREAD

**Issue by Trackhe** [Rat-OS/RatOS#24]
I use the Octopus v1.1 after that Klipper cant connect anymore.
first of all the serial port was wrong after that macro. and after i correct it by uncommend the line in the printer.cfg the same error. i checked the serial ports in linux of the rpi with `ls /dev` but there is no serial like any printer. 
If i try to flash the firmware of the octopus v1.1 the file gets renamed. but this is all i cant getting an connection between the raspberrypi and the octoprint. i use the delivered usb to usbc cable that was delivered and this was workig for the first time. before i used the install macro (vcore pro) i guess this was my mistake, i reset the raspberrypi already.. how can i check that the board is ok?

 ```
 Extruder max_extrude_ratio=0.266081
mcu 'mcu': Starting serial connect
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/btt-octopus-11: [Errno 2] No such file or directory: '/dev/btt-octopus-11'
webhooks client 3044814280: New connection
webhooks client 3044814280: Client info {'program': 'Moonraker', 'version': 'v0.7.1-479-g060ca56'}
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/btt-octopus-11: [Errno 2] No such file or directory: '/dev/btt-octopus-11'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/btt-octopus-11: [Errno 2] No such file or directory: '/dev/btt-octopus-11'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/btt-octopus-11: [Errno 2] No such file or directory: '/dev/btt-octopus-11'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/btt-octopus-11: [Errno 2] No such file or directory: '/dev/btt-octopus-11'
mcu 'mcu': Unable to open serial port: [Errno 2] could not open port /dev/btt-octopus-11: [Errno 2] No such file or directory: '/dev/btt-octopus-11'
 ```

actually the wirering at the back is a mess but i want to be sure that all is working before i assable all fix
![IMG_5726](https://user-images.githubusercontent.com/1494328/160697862-672ad415-e181-45e4-a5dd-2998b9681aba.JPG)

i unpluged the stopkeys because one of them (the cables of the x endstop) was getting hot and the other one is useless because the back what i get blocks from being able to reach the y end key

thats all what i get: 
```
root@ratos:/home/pi/klipper# ls /dev
autofs	       dri	  input  loop6	       mmcblk0boot1  ptmx   ram15  random	   shm	      tty1   tty18  tty26  tty34  tty42  tty50	tty59  ttyAMA0	  vc-mem  vcsa1     vcsu2	 video12
block	       fd	  kmsg	 loop7	       mmcblk0p1     pts    ram2   raw		   snd	      tty10  tty19  tty27  tty35  tty43  tty51	tty6   ttyprintk  vcs	  vcsa2     vcsu3	 video13
btrfs-control  full	  log	 loop-control  mmcblk0p2     ram0   ram3   rfkill	   spidev0.0  tty11  tty2   tty28  tty36  tty44  tty52	tty60  ttyS0	  vcs1	  vcsa3     vcsu4	 video14
cachefiles     fuse	  loop0  mapper        mmcblk0rpmb   ram1   ram4   rpivid-h264mem  spidev0.1  tty12  tty20  tty29  tty37  tty45  tty53	tty61  uhid	  vcs2	  vcsa4     vcsu5	 video15
char	       gpiochip0  loop1  media0        mqueue	     ram10  ram5   rpivid-hevcmem  stderr     tty13  tty21  tty3   tty38  tty46  tty54	tty62  uinput	  vcs3	  vcsa5     vcsu6	 video16
console        gpiochip1  loop2  media1        net	     ram11  ram6   rpivid-intcmem  stdin      tty14  tty22  tty30  tty39  tty47  tty55	tty63  urandom	  vcs4	  vcsa6     vga_arbiter  video18
cuse	       gpiomem	  loop3  mem	       null	     ram12  ram7   rpivid-vp9mem   stdout     tty15  tty23  tty31  tty4   tty48  tty56	tty7   v4l	  vcs5	  vcsm-cma  vhci	 watchdog
disk	       hwrng	  loop4  mmcblk0       port	     ram13  ram8   serial0	   tty	      tty16  tty24  tty32  tty40  tty49  tty57	tty8   vchiq	  vcs6	  vcsu	    video10	 watchdog0
dma_heap       initctl	  loop5  mmcblk0boot0  ppp	     ram14  ram9   serial1	   tty0       tty17  tty25  tty33  tty41  tty5	 tty58	tty9   vcio	  vcsa	  vcsu1     video11	 zero
```
i have connected a csi original raspberrypi camera, that is now shown too at the interface. i dont know if they are one of the /dev serials it can be

**Comment by mystefix81** [comment]
>> If i try to flash the firmware of the octopus v1.1 the file gets renamed. but this is all i cant getting an connection between the raspberrypi and the octoprint.

Did you already tried to use another usb cable ? In my situation the flash process was successful every time (firmware filename was renamed), but i was not able to reach the octopus board over the raspberry pi. Once i replaced the usb cable two times with different ones, the last one was working and the Pi was able to connect to the Octopus board.

**Comment by Trackhe** [comment]
I use a cm4 module with a career board. The problem was the by default deactivated usb. adding dtoverlay=dwc2,dr_mode=host to the /boot/config did this trick. I was able to find out with the command lsusb there was no output.
