### ISSUE TITLE
Make MAYBE_HOME smarter

### ISSUE THREAD

**Issue by ruffle-b** [Rat-OS/RatOS#26]
If one has used SET_CENTER_KINEMATIC_POSITION, MAYBE_HOME 'believes' everything is homed when it isn't; which can result in a nozzle/bed crash.

SET_CENTER_KINEMATIC_POSITION should set a RatOS variable to tell MAYBE_HOME that it needs to do a proper homing run.

**Comment by miklschmidt** [comment]
Fixed in https://github.com/Rat-OS/RatOS-configuration/commit/9eba15763e980819c987388db90643032711bf1f
