### ISSUE TITLE
RTD PT1000

### ISSUE THREAD

**Issue by Johnno88** [Rat-OS/RatOS#27]
I am trying to use a RTD Pt1000 sensor however everything I can find tells me to add it in the "printer.cfg" under the extruder....  After a restart the software comes back with unknown sensor..  

I can not be the first to try this sensor.. Can you please point me in the right direction 

Configuration
RatRig 500
BBT Octopus Pro STM32F446
Raspberry Pi
Extruder LGX
Hotend Mosquito Magnum
Sensor - RTD Pt1000

**Comment by miklschmidt** [comment]
Like it says in the documentation, all overrides happen in your user overrides section. Put your configuration there, ie:

```properties
#############################################################################################################
### USER OVERRIDES
### Anything custom you want to add, or RatOS configuration you want to override, do it here.
#############################################################################################################

[extruder]
sensor_type: PT1000
```
