### ISSUE TITLE
Instructions on website say to download the .zip file to use with balena etcher but its not working 

### ISSUE THREAD

**Issue by pitops** [Rat-OS/RatOS#29]
As the title says Balena etcher expects an image not a .zip file. I think you should fix the website instructions or fix the zip file. (zip file is about 33mb)

```
RASPBERRY PI INSTALLATION
Download the newest release (download the RatOS-*.zip file under the assets dropdown) of [RatOS on github](https://github.com/Rat-Os/RatOS/releases). Then use [Balena Etcher](https://www.balena.io/etcher/) to write that image to the SD card that goes into your raspberry pi (8GB or larger).

Note: this will destroy all data on the card!
```

![Screenshot 2022-05-24 at 11 53 35 PM](https://user-images.githubusercontent.com/9624361/170130321-ae17617f-2a4d-4b16-abd3-70dac32ab70b.png)

Reference on Balena Etcher (https://github.com/balena-io/etcher/issues/1249)

**Comment by miklschmidt** [comment]
You downloaded the source code, not the RatOS image. Download the correct file.
