### ISSUE TITLE
Add support for hidden SSID

### ISSUE THREAD

**Issue by JiMcNulty** [Rat-OS/RatOS#31]
The simple solution is to just add scan_ssid=1

More complex solution is to also add support in the wizard
But I got by with changing it to visible for the wizard and then hide it again

**Comment by miklschmidt** [comment]
This was a conscious choice actually, logic is that if the SSID is hidden, *you prolly want it hidden*. Why is your SSID hidden?

**Comment by miklschmidt** [comment]
Seems like people don't like that choice. If there's a general need for hidden SSID's i'll add it.

**Comment by JiMcNulty** [comment]
> Seems like people don't like that choice. If there's a general need for hidden SSID's i'll add it.

OK thanks for considering it!

**Comment by miklschmidt** [comment]
Support for hidden SSID's has been added to RatOS 2.1
