### ISSUE TITLE
Update to latest version of Raspberry Pi OS

### ISSUE THREAD

**Issue by alidaf** [Rat-OS/RatOS#34]
This will allow more displays to be used as there are more supported in the latest version. In-place upgrades break the installation.

**Comment by sergelhr** [comment]
issue with latest legacy
-e Image has checksum:   9a38607cee9ca6844ee26c1e12fb9d029b567c8235e8b9f78f382a19e6078720
-e Expected checksum:    84c7d41b6d0a9fc8e6163045842a1bae7cc57cef36808d3d350fdf18e9b3f50e
-e
SHA256 Sums dont match! Aborting

**Comment by miklschmidt** [comment]
RatOS follow mainsailOS, afair their next release will be bullseye, and thus the RatOS release after that will be bullseye too.
