### ISSUE TITLE
Text and example wiring for adding 4028 fan can be made more clear

### ISSUE THREAD

**Issue by DocDoo** [Rat-OS/RatOS#35]
Hi 

I tried using the https://github.com/Rat-OS/RatOS/blob/master/site/docs/guides/4028.md documentation to add a 4028 parts fan to my VC3 printer featuring an Octopus 1.1 board. But I got hung up on the text "... PWM wire is fed a 5V PWM signal from the board ..." combined with the image (showing a suggested wiring for an Octopus board) having the voltage selection jump for the Fan port set for 24V.

On discord the community member **Indymusician** helped me get my bearings in this discussion - https://discord.com/channels/582187371529764864/816478223361245204/1015282861227655309

I hope the text and image can be adjusted to better describe how to implement the 4028 fan, but regardless thank you very much for the guide which was really helpful!

**Comment by miklschmidt** [comment]
Clarified here: https://github.com/Rat-OS/RatOS/blob/master/site/docs/guides/4028.md?plain=1#L17

Closing this for now, thanks!
