### ISSUE TITLE
Can't install as any user other than pi

### ISSUE THREAD

**Issue by alidaf** [Rat-OS/RatOS#44]
Using pi as the username is a potential security risk. Using the Raspberry Pi installer and modifying the username and password causes the installation to fail. Running the setup script via SSH fails due to the pi username not existing. The setup script should take a user argument so that it can be installed from the command line.

**Comment by miklschmidt** [comment]
This won't change for the foreseeable future, sorry. Follow the documentation and use Balena Etcher. Your password is much more important than the username, so go change that.
