### ISSUE TITLE
Job details time start/end is set to 1970

### ISSUE THREAD

**Issue by kmlopez-ns** [Rat-OS/RatOS#46]
The start date format on the table is correct, but when you view the full details, it is showing this. See the attached screenshot.

My timezone is +8:00. 

<img width="673" alt="Screenshot 2023-01-11 at 5 44 01 PM" src="https://user-images.githubusercontent.com/121936829/211772580-b2f49b3a-424f-40aa-9ef1-e14dbdf499c4.png">

**Comment by miklschmidt** [comment]
This would be a mainsail issue, so i suggest filing it there (or ask on the mainsail discord). https://github.com/mainsail-crew/mainsail
