### ISSUE TITLE
RatOS v2.0.0 BETA 1 is now available!

### ISSUE THREAD

**Issue by miklschmidt** [Rat-OS/RatOS#53]
We have now reached beta! Go to https://github.com/Rat-OS/RatOS/releases/tag/v2.0.0-beta1 to download the beta release and flash it to your Pi's SD card. You cannot upgrade from alpha to beta without reflashing. 

If you're already on RatOS v2.0.0 beta, you can ignore this message.

Thank you for testing!

**Comment by swilkens** [comment]
Running on RPi4 for my new VCore 3.1 - so far, so good.

Just to check; I assume the "VCore Three" installation is suitable for the v3.1?

**Comment by miklschmidt** [comment]
@swilkens it is yes :)
