### ISSUE TITLE
Do NOT update KlipperScreen

### ISSUE THREAD

**Issue by miklschmidt** [Rat-OS/RatOS#54]
Updating KlipperScreen currently causes a bunch of critical packages to be removed and thus break klipper and moonraker as a result. I'm investigating, and will update you as soon as i know more.

**Comment by 3D-informatik-tienda** [comment]
lo he leído tarde... tampoco actualizar Moonraker... se pierde la conexion

**Comment by 3D-informatik-tienda** [comment]
> Todo lo que puedes hacer es reinstalar. Puede intentar ejecutar `sudo apt-get --fix-broken install`, pero no solucionará todo.

Gracias...

**Comment by Ragaroah** [comment]
Darn... Read this after I updated. Any idea if a fix is incoming, or it's broken so far that a reinstall is needed for sure?

**Comment by miklschmidt** [comment]
@Ragaroah fix is out, but it requires you update Moonraker *before* updating klipperscreen. There was a bug in moonraker where PackageKit installed and removed packages for the wrong architecture. It's now solved. A reinstall and then immediately updating moonraker before updating anything else will fix the problem until Beta2 is out.
