### ISSUE TITLE
octopus pro 446 mcu not found

### ISSUE THREAD

**Issue by mcjohn57** [Rat-OS/RatOS#9]
devlink rule works to map octoprint pro 446 to /dev/btt-octopus-pro-446, but the mcu serial device was still listed as /dev/btt-octopus-11 in config/boards/btt-octopus-pro-446/config.cfg.

thanks for putting this together!

**Comment by miklschmidt** [comment]
Fixed in Rat-OS/RatOS-configuration@d487f3c4682029dbbcf88ee29f11744d193956a5
